version: "3.5"

volumes:
    engine: 
        driver: local
    uiclient: 
        driver: local

services:
    rest-api:
        image: "jcrecio/jkchess-rest-api:latest"
        command: flask run --host=0.0.0.0
        ports:
            - "4018:4018"
        volumes:
            - ./engine:/engine
        depends_on:
            - database
    ng-client:
        image: "jcrecio/jkchess-ng-client:latest"
        command: > 
            bash -c "npm install && ng serve --host 0.0.0.0 --port 4019"        
        ports:
            - "4019:4019"
        volumes:
            - './ng-client:/usr/src/app'
    database:
        image: mongo:latest
        ports:
            - "27018:27018"