version: "3.5"

volumes:
    engine: 
        driver: local
    uiclient: 
        driver: local

services:
    restapi:
        image: "jcrecio/globalchess-restapi:latest"
        command: flask run --host=0.0.0.0
        ports:
            - "4018:4018"
        volumes:
            - ./engine:/restapi/engine
        depends_on:
            - database
    uiclient:
        image: "jcrecio/globalchess-uiclient:latest"
        command: > 
            bash -c "npm install && ng serve --host 0.0.0.0 --port 4019"        
        ports:
            - "4019:4019"
        volumes:
            - './uiclient:/usr/src/app'
    database:
        image: mongo:latest
        ports:
            - "27018:27018"